channels:
- conda-forge
- defaults
dependencies:
- click=8.1.7
- ipykernel=6.29.3
- matplotlib=3.8.4
- matplotlib-venn=0.11.10
- numpy=1.26.4
- openpyxl=3.1.2
- pandas=2.2.2
- python=3.12.3
- python-dotenv=1.0.1
- pyyaml=6.0.1
- seaborn=0.13.2
name: grd-interno
